micronaut:
  application:
    name: desafioPixRest
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update


grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    desafioPix:
      addres: http://localhost:50051
jackson.serialization.writeDateAsTimestamps: false
